### ISSUE TITLE
Move micro to use cobra/viper

### ISSUE THREAD

**Issue by asim** [m3o/dev#302] opened 2020-08-01 22:02 UTC
Cobra and Viper will be simpler solutions for us to manage both command line flags but also the user config file that lives at ~/.micro/config.json. In doing so we should evaluate how we're setting up the command line and try separate what is the CLI version server and services requirements. CLI and related things like api, proxy, web, etc should essentially be dumb clients.

**Comment by domwong** [comment] 2020-08-07 14:22
dupe of #211

**Closed by domwong** 2020-08-07 14:22 UTC
